spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8484/auth/realms/test/protocol/openid-connect/certs"

csv:
  path: "src/main/resources/cities.csv"

auth:
  enabled: true
